.TH PASS-LN 1
.SH NAME
pass ln \- Pass extension for creating symbolic links
.SH SYNOPSIS
.B pass ln
\fITARGET\fR
\fILINK_NAME\fR
.br
.B pass ln
\fITARGET\fR
\fIDIRECTORY/\fR
.SH DESCRIPTION
In the first form, create an entry in the password store named
\fILINK_NAME\fR which acts as an alias to an existing entry named
\fITARGET\fR.  This is implemented by creating a symbolic link at
\fILINK_NAME\fR.  Both \fITARGET\fR and \fILINK_NAME\fR must be
relative to the root of the password store, but \fITARGET\fR is
automatically converted to a path relative to \fILINK_NAME\fR's parent
directory when creating the symbolic link, to ensure it can be
dereferenced correctly.  Note that \fITARGET\fR may be either a file
(with no \fB.gpg\fR suffix) or directory.
.PP
The second form is equivalent to the first form except that
\fILINK_NAME\fR is implicitly postpended with the last component of
\fITARGET\fR, as in the \fBln -s\fR command.  This is provided as a
convenience and does not create any additional functionality.
.PP
Unlike with \fBln -s\fR, this command automatically creates all parent
directories of \fILINK_NAME\fR, including \fILINK_NAME\fR itself if it
does not exist but the provided name has a trailing slash.
.SH OPTIONS
This command has no options.
.SH EXIT STATUS
This command follows the standard convention of a zero exit status
indicating success.  No guarantees are made about the exit status on
an error except that it will be nonzero.
.SH EXAMPLES
Make it possible to log in to various Stack Exchange sites using a
single set of credentials:
.PP
.\"Weird indentation style to workaround man bug on BSD/macOS
.in +3n
.EX

 % pass insert stackexchange.com/you@example.com
 % pass ln stackexchange.com stackoverflow.com
 % pass ln stackexchange.com askubuntu.com
 % pass ln stackexchange.com mathoverflow.com

.EE
.in
.PP
Create a human-readable alias for a piece of identifying information:
.PP
.in +3n
.EX

 % pass insert insurance-card/rxgrp
 % pass ln
     wallet/insurance-card/rxgrp
     wallet/insurance-card/prescription-group-number

.EE
.in
.PP
Create an alias for a directory and associate it with a specific
domain:
.PP
.in +3n
.EX

 % pass ln wallet/insurance-card cigna.com/id-card

.EE
.in
.SH NOTES
There is no option to overwrite an existing file or directory with a
symbolic link. To do this, first \fBpass rm\fR the existing file or
directory, then create the symbolic link with \fBpass ln\fR.
.SH BUGS
You cannot use \fBpass insert\fR to insert an entry into a directory
through a symlink (e.g. if \fBfoo\fR is a symlink pointing to
directory \fBbar\fR, then \fBpass insert foo/quux\fR will fail even
though \fBpass insert bar/quux\fR is fine). The error is \fBfatal:
pathspec '/home/yourname/.password-store/foo/quux.gpg' is beyond a
symbolic link\fR. This is a bug in Pass and cannot be fixed in
pass-ln. Unfortunately, Pass does not have a bug tracker, so there is
no upstream reference for the bug.
.PP
The output of \fBpass ls\fR may be unexpected in the face of symbolic
links. In particular, you may see the text \fB[recursive, not
followed]\fR after a symbolic link. This is normal, and indicates that
the contents of the directory that the symlink is pointing to have
already been displayed in the current output, and \fBtree\fR is
refraining from showing the same information a second time.
.PP
Autocompletion for \fBpass ln\fR does not work in Fish. Unfortunately,
this is due to a bug in Pass which causes it to ignore Pass extensions
when generating autocompletions, and there is no way to fix this in
pass-ln.
.SH AUTHOR
Written by Radon Rosborough <radon.neon@gmail.com>.
.SH COPYRIGHT
Copyright \(co 2022 Radon Rosborough and licensed under the MIT
License.
.SH "SEE ALSO"
The source code and bug tracker for \fBpass ln\fR may be found at
<https://github.com/raxod502/pass-ln>.

.ig
Local Variables:
sentence-end-double-space: t
End:
..
