name: Tests
on: [push, pull_request]
jobs:
  shellspec:
    runs-on: ubuntu-24.04
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v2
      - run: ./ci/github-actions.bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
